### ISSUE TITLE
Shows error message in Vim would be perfect

### ISSUE THREAD

**Issue by orklann** [tweekmonster/gofmt.vim#2]
`gofmt` command line will shows error message if the .go file has some syntax errors, and would not format the .go file. So if any improvement in this plugin to show errors as well in Vim window after saving .go file which has syntax error?

I like this little plugin, and it works fine.

**Comment by orklann** [comment]
I tried to hack gofmt.vim, and changed `autoload/gofmt.vim`, line `70`

from:

```vim
  if v:shell_error != 0
    return
  endif
```
to

```vim
  if v:shell_error != 0
    echohl ErrorMsg
    echo "gofmt errors!"
    return ''
  endif
```

and it  shows error message at the bottom if gofmt encounter any error.

**Comment by tweekmonster** [comment]
@orklann Sorry for the long delay.  If you want to create a PR, I wouldn't mind a single line message informing the user just as long as it's an optional feature.  I made the error silent because I use Neomake for linting and error-checking.

**Comment by orklann** [comment]
I made a PR on this issue.
